import type { ReactNode } from 'react';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js Contentful Sample',
  description: 'Generated by create next app',
};

const RootLayout: (props: {
  children: ReactNode;
}) => Promise<JSX.Element> = async ({ children }) => {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
